"""make keycloak_sub nullable

Revision ID: 52f25dfd8b03
Revises: b7b01accf86e
Create Date: 2026-07-21 21:59:06.265416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f25dfd8b03'
down_revision: Union[str, Sequence[str], None] = 'b7b01accf86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'keycloak_sub',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'keycloak_sub',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
